chore: replace obsolete doc_auto_cfg feature with doc_cfg (#143)
Or else we get this:
```
error[E0557]: feature has been removed
  --> src/lib.rs:22:29
   |
22 | #![cfg_attr(docsrs, feature(doc_auto_cfg))]
   |                             ^^^^^^^^^^^^ feature has been removed
   |
   = note: removed in 1.58.0; see <https://github.com/rust-lang/rust/pull/138907> for more information
   = note: merged into `doc_cfg`
```

which block CI.

---------

Signed-off-by: sagudev <16504129+sagudev@users.noreply.github.com>